### ISSUE TITLE
No Platform

### ISSUE THREAD

**Issue by daltondanis** [Riptail-Games/TDSG#1]
**Are we going to use:**
## **react-game-kit:**

- https://github.com/FormidableLabs/react-game-kit
- https://formidable.com/blog/2016/09/15/introducing-react-game-kit/

## **No game-kits:**

- https://medium.com/@miguelhaba/my-first-game-with-react-native-40a83aa91274
- - https://github.com/GeekyAnts/react-native-easy-grid

## **Or fully coded:**

- Plain old HTML, Javascript, Typescript, and CSS with many functions to create:
- - game boards
- - animation
- - functionality
- - etc..

**Comment by riptailgames** [comment]
check the asana task for gamekit. all the info is there

**Comment by riptailgames** [comment]
all info on tasks and discussions will be in asana
